# MR_app/.streamlit/secrets.toml

[formspree]
# Either store the full endpoint:
endpoint = "https://formspree.io/f/xeorjldp"
# …or store just the id and build it in code:
# id = "xeorjldp"

[mail]
sender = "no-reply@markmentum.io"

# .streamlit/secrets.toml
#OPENAI_API_KEY =""